begin;

create table if not exists public.vf_municipalities (
  id bigint generated by default as identity primary key,
  name text not null,
  state text not null default 'PR',
  ibge_code text,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now(),
  created_by uuid,
  constraint vf_municipalities_name_state_unique unique (name, state)
);

alter table public.vf_municipalities enable row level security;

drop policy if exists vf_municipalities_select on public.vf_municipalities;
create policy vf_municipalities_select on public.vf_municipalities
for select to anon, authenticated
using (status = 'active');

insert into public.vf_municipalities(name,state,status)
values ('Arapongas','PR','active')
on conflict (name,state) do update set status='active';

create or replace function private.vf_default_municipality_id()
returns bigint
language sql
stable
set search_path = ''
as $$
  select id from public.vf_municipalities
  where name='Arapongas' and state='PR'
  order by id limit 1;
$$;

create table if not exists public.vf_user_municipalities (
  user_id bigint not null references public.vf_users(id) on delete cascade,
  municipality_id bigint not null references public.vf_municipalities(id) on delete cascade,
  access_role text not null check (access_role in ('adm','master','lideranca','liderado','eleitor')),
  status text not null default 'active' check (status in ('active','blocked')),
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (user_id, municipality_id)
);

alter table public.vf_user_municipalities enable row level security;

drop policy if exists vf_user_municipalities_select on public.vf_user_municipalities;
create policy vf_user_municipalities_select on public.vf_user_municipalities
for select to authenticated
using (
  user_id in (select id from public.vf_users where auth_user_id = (select auth.uid()))
  or (select private.vf_is_adm())
);

insert into public.vf_user_municipalities(user_id, municipality_id, access_role, status, is_default)
select u.id, private.vf_default_municipality_id(), u.access_role, u.status, true
from public.vf_users u
on conflict (user_id, municipality_id) do update
set access_role=excluded.access_role, status=excluded.status, is_default=true;

create table if not exists public.vf_signup_requests (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  email text not null,
  name text not null,
  municipality_name text not null,
  state text not null default 'PR',
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by bigint references public.vf_users(id),
  review_note text
);

alter table public.vf_signup_requests enable row level security;

drop policy if exists vf_signup_requests_self_select on public.vf_signup_requests;
create policy vf_signup_requests_self_select on public.vf_signup_requests
for select to authenticated
using (auth_user_id = (select auth.uid()) or (select private.vf_is_adm()));

alter table public.vf_owned_records add column if not exists municipality_id bigint references public.vf_municipalities(id);
alter table public.vf_contact_exports add column if not exists municipality_id bigint references public.vf_municipalities(id);
alter table public.vf_audit_logs add column if not exists municipality_id bigint references public.vf_municipalities(id);
alter table public.vf_user_invitations add column if not exists municipality_id bigint references public.vf_municipalities(id);

update public.vf_owned_records set municipality_id=private.vf_default_municipality_id() where municipality_id is null;
update public.vf_contact_exports set municipality_id=private.vf_default_municipality_id() where municipality_id is null;
update public.vf_audit_logs set municipality_id=private.vf_default_municipality_id() where municipality_id is null;
update public.vf_user_invitations set municipality_id=private.vf_default_municipality_id() where municipality_id is null;

alter table public.vf_owned_records alter column municipality_id set default private.vf_default_municipality_id();
alter table public.vf_contact_exports alter column municipality_id set default private.vf_default_municipality_id();
alter table public.vf_audit_logs alter column municipality_id set default private.vf_default_municipality_id();
alter table public.vf_user_invitations alter column municipality_id set default private.vf_default_municipality_id();

alter table public.vf_owned_records alter column municipality_id set not null;
alter table public.vf_contact_exports alter column municipality_id set not null;
alter table public.vf_audit_logs alter column municipality_id set not null;
alter table public.vf_user_invitations alter column municipality_id set not null;

create index if not exists vf_owned_records_municipality_idx on public.vf_owned_records(municipality_id, kind, id);
create index if not exists vf_contact_exports_municipality_idx on public.vf_contact_exports(municipality_id, created_at desc);
create index if not exists vf_audit_logs_municipality_idx on public.vf_audit_logs(municipality_id, created_at desc);
create index if not exists vf_user_invitations_municipality_idx on public.vf_user_invitations(municipality_id, status, created_at desc);
create index if not exists vf_user_municipalities_municipality_idx on public.vf_user_municipalities(municipality_id, status, access_role);

create or replace function private.vf_register_signup_request_internal(p_municipality_name text, p_state text default 'PR')
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := (select auth.uid());
  au auth.users;
  req public.vf_signup_requests;
  requested_name text := trim(coalesce(p_municipality_name,''));
  requested_state text := upper(trim(coalesce(p_state,'PR')));
begin
  if uid is null then raise exception 'Não autenticado' using errcode='42501'; end if;
  select * into au from auth.users where id=uid;
  if au.id is null then raise exception 'Conta Auth não encontrada' using errcode='42501'; end if;
  if au.email_confirmed_at is null then raise exception 'Confirme seu e-mail antes de solicitar acesso'; end if;
  if requested_name='' or requested_state='' then raise exception 'Município obrigatório'; end if;
  if exists (select 1 from public.vf_users where auth_user_id=uid) then
    return jsonb_build_object('status','already_active');
  end if;
  if exists (select 1 from public.vf_user_invitations where lower(email)=lower(coalesce(au.email,'')) and status='pending' and expires_at>now()) then
    return jsonb_build_object('status','invited');
  end if;
  insert into public.vf_signup_requests(auth_user_id,email,name,municipality_name,state,status)
  values(uid, lower(trim(coalesce(au.email,''))), trim(coalesce(au.raw_user_meta_data->>'name','Usuário')), requested_name, requested_state, 'pending')
  on conflict (auth_user_id) do update set
    municipality_name=excluded.municipality_name,
    state=excluded.state,
    name=excluded.name,
    email=excluded.email,
    status=case when public.vf_signup_requests.status='approved' then public.vf_signup_requests.status else 'pending' end,
    requested_at=case when public.vf_signup_requests.status='approved' then public.vf_signup_requests.requested_at else now() end
  returning * into req;
  return jsonb_build_object('id',req.id,'status',req.status,'municipalityName',req.municipality_name,'state',req.state);
end;
$$;

create or replace function public.vf_register_signup_request(p_municipality_name text, p_state text default 'PR')
returns jsonb
language sql
set search_path=''
as $$ select private.vf_register_signup_request_internal(p_municipality_name,p_state); $$;

revoke all on function public.vf_register_signup_request(text,text) from public, anon;
grant execute on function public.vf_register_signup_request(text,text) to authenticated;

create or replace function private.vf_my_municipalities_internal()
returns jsonb
language plpgsql
security definer
stable
set search_path=''
as $$
declare uid uuid := (select auth.uid());
begin
  if uid is null then raise exception 'Não autenticado' using errcode='42501'; end if;
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id',m.id,'name',m.name,'state',m.state,'accessRole',um.access_role,
      'status',um.status,'isDefault',um.is_default
    ) order by um.is_default desc,m.name)
    from public.vf_users u
    join public.vf_user_municipalities um on um.user_id=u.id
    join public.vf_municipalities m on m.id=um.municipality_id
    where u.auth_user_id=uid and um.status='active' and m.status='active'
  ),'[]'::jsonb);
end;
$$;

create or replace function public.vf_my_municipalities()
returns jsonb
language sql stable set search_path=''
as $$ select private.vf_my_municipalities_internal(); $$;
revoke all on function public.vf_my_municipalities() from public, anon;
grant execute on function public.vf_my_municipalities() to authenticated;

commit;