create table if not exists public.vf_whatsapp_campaigns (
  id uuid primary key default gen_random_uuid(),
  actor_user_id bigint references public.vf_users(id) on delete set null,
  actor_email text not null,
  status text not null default 'running'
    check (status in ('queued','running','paused','completed','cancelled','failed')),
  template_name text not null,
  template_language text not null default 'pt_BR',
  delay_seconds integer not null default 3 check (delay_seconds between 1 and 120),
  total_count integer not null default 0 check (total_count >= 0),
  waiting_count integer not null default 0 check (waiting_count >= 0),
  sending_count integer not null default 0 check (sending_count >= 0),
  sent_count integer not null default 0 check (sent_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  cancelled_count integer not null default 0 check (cancelled_count >= 0),
  uncertain_count integer not null default 0 check (uncertain_count >= 0),
  next_dispatch_at timestamptz not null default now(),
  last_worker_at timestamptz,
  started_at timestamptz not null default now(),
  paused_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.vf_whatsapp_campaign_items (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.vf_whatsapp_campaigns(id) on delete cascade,
  sequence integer not null,
  contact_record_id text,
  contact_name text not null default 'Contato',
  phone text not null,
  parameters jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'waiting'
    check (status in ('waiting','sending','sent','failed','cancelled','uncertain')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  max_attempts integer not null default 3 check (max_attempts between 1 and 10),
  next_attempt_at timestamptz not null default now(),
  lock_token uuid,
  locked_at timestamptz,
  lock_expires_at timestamptz,
  message_id text,
  error_code text,
  error_message text,
  provider_response jsonb not null default '{}'::jsonb,
  sent_at timestamptz,
  failed_at timestamptz,
  cancelled_at timestamptz,
  uncertain_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, phone),
  unique (campaign_id, sequence)
);

create index if not exists vf_whatsapp_campaigns_worker_idx
  on public.vf_whatsapp_campaigns(status, next_dispatch_at, created_at);
create index if not exists vf_whatsapp_campaign_items_queue_idx
  on public.vf_whatsapp_campaign_items(campaign_id, status, next_attempt_at, sequence);
create index if not exists vf_whatsapp_campaign_items_lock_idx
  on public.vf_whatsapp_campaign_items(status, lock_expires_at);
create index if not exists vf_whatsapp_campaign_items_phone_idx
  on public.vf_whatsapp_campaign_items(phone);

alter table public.vf_whatsapp_campaigns enable row level security;
alter table public.vf_whatsapp_campaign_items enable row level security;

revoke all on public.vf_whatsapp_campaigns from anon, authenticated;
revoke all on public.vf_whatsapp_campaign_items from anon, authenticated;

create or replace function public.vf_whatsapp_queue_create_campaign(
  p_actor_user_id bigint,
  p_actor_email text,
  p_template_name text,
  p_template_language text,
  p_delay_seconds integer,
  p_items jsonb,
  p_metadata jsonb default '{}'::jsonb
) returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_campaign_id uuid;
  v_total integer;
begin
  if jsonb_typeof(p_items) <> 'array' then
    raise exception 'p_items must be a JSON array';
  end if;

  v_total := jsonb_array_length(p_items);
  if v_total < 1 or v_total > 5000 then
    raise exception 'campaign item count must be between 1 and 5000';
  end if;

  if coalesce(trim(p_template_name), '') = '' then
    raise exception 'template name is required';
  end if;

  insert into public.vf_whatsapp_campaigns (
    actor_user_id,
    actor_email,
    status,
    template_name,
    template_language,
    delay_seconds,
    total_count,
    waiting_count,
    metadata
  ) values (
    p_actor_user_id,
    lower(trim(p_actor_email)),
    'running',
    trim(p_template_name),
    coalesce(nullif(trim(p_template_language), ''), 'pt_BR'),
    greatest(1, least(120, coalesce(p_delay_seconds, 3))),
    v_total,
    v_total,
    coalesce(p_metadata, '{}'::jsonb)
  )
  returning id into v_campaign_id;

  insert into public.vf_whatsapp_campaign_items (
    campaign_id,
    sequence,
    contact_record_id,
    contact_name,
    phone,
    parameters,
    metadata
  )
  select
    v_campaign_id,
    ordinality::integer,
    nullif(item->>'contactId', ''),
    coalesce(nullif(trim(item->>'name'), ''), 'Contato'),
    regexp_replace(coalesce(item->>'phone', ''), '\D', '', 'g'),
    case
      when jsonb_typeof(item->'parameters') = 'array' then item->'parameters'
      else '[]'::jsonb
    end,
    coalesce(item->'metadata', '{}'::jsonb)
  from jsonb_array_elements(p_items) with ordinality as x(item, ordinality);

  if exists (
    select 1
    from public.vf_whatsapp_campaign_items
    where campaign_id = v_campaign_id
      and (length(phone) < 12 or length(phone) > 15)
  ) then
    raise exception 'campaign contains invalid phone numbers';
  end if;

  return v_campaign_id;
end;
$$;

create or replace function public.vf_whatsapp_queue_recover_stale()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_count integer := 0;
begin
  with stale as (
    update public.vf_whatsapp_campaign_items
    set
      status = 'uncertain',
      uncertain_at = now(),
      error_code = coalesce(error_code, 'worker_lease_expired'),
      error_message = coalesce(error_message, 'Envio ficou sem confirmação após interrupção do worker. Requer conferência antes de reenviar.'),
      lock_token = null,
      locked_at = null,
      lock_expires_at = null,
      updated_at = now()
    where status = 'sending'
      and lock_expires_at is not null
      and lock_expires_at < now()
    returning campaign_id
  ),
  grouped as (
    select campaign_id, count(*)::integer as qty
    from stale
    group by campaign_id
  )
  update public.vf_whatsapp_campaigns c
  set
    sending_count = greatest(0, c.sending_count - g.qty),
    uncertain_count = c.uncertain_count + g.qty,
    updated_at = now()
  from grouped g
  where c.id = g.campaign_id;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.vf_whatsapp_queue_claim_next()
returns table (
  item_id bigint,
  campaign_id uuid,
  lock_token uuid,
  phone text,
  contact_name text,
  parameters jsonb,
  item_metadata jsonb,
  template_name text,
  template_language text,
  delay_seconds integer,
  attempt_count integer
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_campaign public.vf_whatsapp_campaigns%rowtype;
  v_item public.vf_whatsapp_campaign_items%rowtype;
  v_lock uuid;
begin
  perform public.vf_whatsapp_queue_recover_stale();

  select c.*
    into v_campaign
  from public.vf_whatsapp_campaigns c
  where c.status = 'running'
    and c.next_dispatch_at <= now()
    and exists (
      select 1
      from public.vf_whatsapp_campaign_items i
      where i.campaign_id = c.id
        and i.status = 'waiting'
        and i.next_attempt_at <= now()
    )
  order by c.created_at, c.id
  for update skip locked
  limit 1;

  if not found then
    return;
  end if;

  select i.*
    into v_item
  from public.vf_whatsapp_campaign_items i
  where i.campaign_id = v_campaign.id
    and i.status = 'waiting'
    and i.next_attempt_at <= now()
  order by i.sequence, i.id
  for update skip locked
  limit 1;

  if not found then
    return;
  end if;

  v_lock := gen_random_uuid();

  update public.vf_whatsapp_campaign_items
  set
    status = 'sending',
    attempt_count = attempt_count + 1,
    lock_token = v_lock,
    locked_at = now(),
    lock_expires_at = now() + interval '2 minutes',
    error_code = null,
    error_message = null,
    updated_at = now()
  where id = v_item.id;

  update public.vf_whatsapp_campaigns
  set
    waiting_count = greatest(0, waiting_count - 1),
    sending_count = sending_count + 1,
    next_dispatch_at = clock_timestamp() + make_interval(secs => delay_seconds),
    last_worker_at = now(),
    updated_at = now()
  where id = v_campaign.id;

  return query
  select
    v_item.id,
    v_campaign.id,
    v_lock,
    v_item.phone,
    v_item.contact_name,
    v_item.parameters,
    v_item.metadata,
    v_campaign.template_name,
    v_campaign.template_language,
    v_campaign.delay_seconds,
    v_item.attempt_count + 1;
end;
$$;

create or replace function public.vf_whatsapp_queue_finish_item(
  p_item_id bigint,
  p_lock_token uuid,
  p_outcome text,
  p_message_id text default null,
  p_error_code text default null,
  p_error_message text default null,
  p_provider_response jsonb default '{}'::jsonb,
  p_retry_delay_seconds integer default 60
) returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_item public.vf_whatsapp_campaign_items%rowtype;
  v_campaign_status text;
begin
  select *
    into v_item
  from public.vf_whatsapp_campaign_items
  where id = p_item_id
    and status = 'sending'
    and lock_token = p_lock_token
  for update;

  if not found then
    return false;
  end if;

  if p_outcome = 'sent' then
    update public.vf_whatsapp_campaign_items
    set
      status = 'sent',
      message_id = nullif(p_message_id, ''),
      provider_response = coalesce(p_provider_response, '{}'::jsonb),
      sent_at = now(),
      lock_token = null,
      locked_at = null,
      lock_expires_at = null,
      updated_at = now()
    where id = p_item_id;

    update public.vf_whatsapp_campaigns
    set
      sending_count = greatest(0, sending_count - 1),
      sent_count = sent_count + 1,
      updated_at = now()
    where id = v_item.campaign_id;

  elsif p_outcome = 'retry' and v_item.attempt_count < v_item.max_attempts then
    update public.vf_whatsapp_campaign_items
    set
      status = 'waiting',
      next_attempt_at = now() + make_interval(secs => greatest(15, least(3600, coalesce(p_retry_delay_seconds, 60)))),
      error_code = nullif(p_error_code, ''),
      error_message = nullif(p_error_message, ''),
      provider_response = coalesce(p_provider_response, '{}'::jsonb),
      lock_token = null,
      locked_at = null,
      lock_expires_at = null,
      updated_at = now()
    where id = p_item_id;

    update public.vf_whatsapp_campaigns
    set
      sending_count = greatest(0, sending_count - 1),
      waiting_count = waiting_count + 1,
      updated_at = now()
    where id = v_item.campaign_id;

  elsif p_outcome = 'uncertain' then
    update public.vf_whatsapp_campaign_items
    set
      status = 'uncertain',
      uncertain_at = now(),
      error_code = coalesce(nullif(p_error_code, ''), 'delivery_uncertain'),
      error_message = coalesce(nullif(p_error_message, ''), 'A entrega não pôde ser confirmada com segurança. O item não será reenviado automaticamente.'),
      provider_response = coalesce(p_provider_response, '{}'::jsonb),
      lock_token = null,
      locked_at = null,
      lock_expires_at = null,
      updated_at = now()
    where id = p_item_id;

    update public.vf_whatsapp_campaigns
    set
      sending_count = greatest(0, sending_count - 1),
      uncertain_count = uncertain_count + 1,
      updated_at = now()
    where id = v_item.campaign_id;

  else
    update public.vf_whatsapp_campaign_items
    set
      status = 'failed',
      failed_at = now(),
      error_code = nullif(p_error_code, ''),
      error_message = nullif(p_error_message, ''),
      provider_response = coalesce(p_provider_response, '{}'::jsonb),
      lock_token = null,
      locked_at = null,
      lock_expires_at = null,
      updated_at = now()
    where id = p_item_id;

    update public.vf_whatsapp_campaigns
    set
      sending_count = greatest(0, sending_count - 1),
      failed_count = failed_count + 1,
      updated_at = now()
    where id = v_item.campaign_id;
  end if;

  select status
    into v_campaign_status
  from public.vf_whatsapp_campaigns
  where id = v_item.campaign_id;

  if v_campaign_status in ('running','queued') and not exists (
    select 1
    from public.vf_whatsapp_campaign_items
    where campaign_id = v_item.campaign_id
      and status in ('waiting','sending')
  ) then
    update public.vf_whatsapp_campaigns
    set
      status = 'completed',
      completed_at = now(),
      updated_at = now()
    where id = v_item.campaign_id;
  end if;

  return true;
end;
$$;

create or replace function public.vf_whatsapp_queue_campaign_action(
  p_campaign_id uuid,
  p_action text
) returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_changed integer := 0;
begin
  if p_action = 'pause' then
    update public.vf_whatsapp_campaigns
    set status = 'paused', paused_at = now(), updated_at = now()
    where id = p_campaign_id and status in ('running','queued');
    return found;
  elsif p_action = 'resume' then
    update public.vf_whatsapp_campaigns
    set status = 'running', paused_at = null, next_dispatch_at = least(next_dispatch_at, now()), updated_at = now()
    where id = p_campaign_id and status = 'paused';
    return found;
  elsif p_action = 'cancel' then
    update public.vf_whatsapp_campaigns
    set status = 'cancelled', cancelled_at = now(), updated_at = now()
    where id = p_campaign_id and status in ('running','queued','paused');

    if not found then
      return false;
    end if;

    with cancelled as (
      update public.vf_whatsapp_campaign_items
      set
        status = 'cancelled',
        cancelled_at = now(),
        updated_at = now()
      where campaign_id = p_campaign_id
        and status = 'waiting'
      returning id
    )
    select count(*)::integer into v_changed from cancelled;

    update public.vf_whatsapp_campaigns
    set
      waiting_count = greatest(0, waiting_count - v_changed),
      cancelled_count = cancelled_count + v_changed,
      updated_at = now()
    where id = p_campaign_id;

    return true;
  end if;

  raise exception 'unsupported campaign action: %', p_action;
end;
$$;

revoke all on function public.vf_whatsapp_queue_create_campaign(bigint,text,text,text,integer,jsonb,jsonb) from public, anon, authenticated;
revoke all on function public.vf_whatsapp_queue_recover_stale() from public, anon, authenticated;
revoke all on function public.vf_whatsapp_queue_claim_next() from public, anon, authenticated;
revoke all on function public.vf_whatsapp_queue_finish_item(bigint,uuid,text,text,text,text,jsonb,integer) from public, anon, authenticated;
revoke all on function public.vf_whatsapp_queue_campaign_action(uuid,text) from public, anon, authenticated;

grant all on public.vf_whatsapp_campaigns to service_role;
grant all on public.vf_whatsapp_campaign_items to service_role;
grant usage, select on sequence public.vf_whatsapp_campaign_items_id_seq to service_role;
grant execute on function public.vf_whatsapp_queue_create_campaign(bigint,text,text,text,integer,jsonb,jsonb) to service_role;
grant execute on function public.vf_whatsapp_queue_recover_stale() to service_role;
grant execute on function public.vf_whatsapp_queue_claim_next() to service_role;
grant execute on function public.vf_whatsapp_queue_finish_item(bigint,uuid,text,text,text,text,jsonb,integer) to service_role;
grant execute on function public.vf_whatsapp_queue_campaign_action(uuid,text) to service_role;
