insert into public.vf_arapongas_district_aliases (alias_key, canonical_name, active, updated_at)
values
('AT DA BOA VISTA','Jardim Alto da Boa Vista',true,now()),
('AT DA B VISTA','Jardim Alto da Boa Vista',true,now()),
('ALTA BOA VISTA','Jardim Alto da Boa Vista',true,now()),
('AT BOA VISTA','Jardim Alto da Boa Vista',true,now()),
('AT DA BOA VIS','Jardim Alto da Boa Vista',true,now()),
('AT DA BOA VISATA','Jardim Alto da Boa Vista',true,now()),
('JARDIM ALTO BOAS VISTA','Jardim Alto da Boa Vista',true,now()),
('JARDIM ALTO DA BOA V','Jardim Alto da Boa Vista',true,now()),
('ARAICANDUVA','Aricanduva',true,now()),
('ARAPONGUINHA VL','Vila Araponguinha',true,now()),
('ARAPONGUINHAS','Vila Araponguinha',true,now()),
('VILA ARAPONGUIN','Vila Araponguinha',true,now()),
('CONJUNTO HAB PE CHICO','Conjunto Padre Chico',true,now()),
('CJTO PE CHICO','Conjunto Padre Chico',true,now()),
('CONJUNTO PE BERNARDO','Conjunto Padre Bernardo Merckel',true,now()),
('CONJUNTO P BERNARDO','Conjunto Padre Bernardo Merckel',true,now()),
('CONJUNTO PE B MERCKE','Conjunto Padre Bernardo Merckel',true,now()),
('CONJUNTO PE BERNARDO MERCK','Conjunto Padre Bernardo Merckel',true,now()),
('CONJUNTO ULISSES GUI','Conjunto Ulisses Guimarães',true,now()),
('CONJUNTO ULISSE','Conjunto Ulisses Guimarães',true,now()),
('CONJUNTO ULISSES G','Conjunto Ulisses Guimarães',true,now()),
('CONJUNTO ULISSES GUIMARA','Conjunto Ulisses Guimarães',true,now()),
('JARDIM NOVA BAR','Jardim Nova Baroneza',true,now()),
('JARDIM AER','Jardim Aeroporto',true,now()),
('JARDIM AROPORTO','Jardim Aeroporto',true,now()),
('VILA INDUSTRIA','Vila Industrial',true,now()),
('APARECIDA VL','Vila Aparecida',true,now()),
('JDM PRIMAVERA','Jardim Primavera',true,now()),
('JARDIM PRIMAVER','Jardim Primavera',true,now()),
('PRIMAVERA JD','Jardim Primavera',true,now()),
('STA EFIGENIA','Jardim Santa Efigênia',true,now()),
('VILA 33','Vila Trinta e Três',true,now()),
('VILA BERNARDO','Vila Bernardes',true,now()),
('BONONI JD','Jardim Bononi',true,now()),
('D MARTINA','Jardim Dona Martinha',true,now()),
('DN MARTINHA','Jardim Dona Martinha',true,now()),
('CENTR','Centro',true,now()),
('CENTAUROS','Conjunto Centauro',true,now()),
('CONJUNTO CENTAU','Conjunto Centauro',true,now()),
('COLOMBIA 4','Jardim Colúmbia IV',true,now()),
('COLOMBIA TRES','Jardim Colúmbia III',true,now()),
('JARDIM COLUMBIA 3','Jardim Colúmbia III',true,now()),
('COLUMBIA II','Jardim Colúmbia II',true,now()),
('CARAVELE','Jardim Caravelle',true,now()),
('CARAVELI','Jardim Caravelle',true,now()),
('CARAVELLE','Jardim Caravelle',true,now()),
('JARDIM CARAVELA','Jardim Caravelle',true,now()),
('JARDIM CARAVELI','Jardim Caravelle',true,now()),
('JARDIM DOS PASSARO','Jardim dos Pássaros',true,now()),
('JARDIM S CRISTOVA','Jardim São Cristóvão',true,now())
on conflict (alias_key) do nothing;

select * from public.vf_refresh_arapongas_district_summary();
select * from public.vf_refresh_contact_location_issues();
