/**
 * Catálogo Oficial de Locais de Votação e Resultados Eleitorais Públicos do TSE
 * 61ª Zona Eleitoral - Arapongas / PR e Referências Oficiais do Paraná
 * Estrutura Genérica e Extensível para Todos os Cargos, Candidatos e Eleições
 */

export type PollingPlace = {
  id: string;
  name: string;
  shortName?: string;
  address: string;
  district: string;
  zone: string;
  sections: number[];
  sectionsCount: number;
  totalVoters: number;
  latitude?: number;
  longitude?: number;
};

export type CandidateRunningMate = {
  name: string;
  fullName?: string;
  ballotNumber?: number | string;
  party?: string;
  roleLabel: "Vice-Presidente" | "Vice-Governador" | "Vice-Prefeito" | "1º Suplente" | "2º Suplente" | "Suplente";
};

export type CandidateResult = {
  name: string; // Nome de urna
  fullName?: string; // Nome completo oficial
  ballotNumber: number | string; // Número do candidato
  party: string; // Sigla do partido
  partyName?: string; // Nome do partido
  coalition?: string; // Coligação
  office?: string; // Cargo disputado
  votes: number; // Votos válidos obtidos
  percentage: number; // Percentual dos votos válidos
  elected?: boolean; // Se foi eleito
  situation?: "Eleito por QP" | "Eleito por média" | "Eleito" | "2º Turno" | "Suplente" | "Não Eleito" | "Indeferido" | "Renúncia";
  runningMate?: CandidateRunningMate; // Vice ou Suplente
  photoUrl?: string;
};

export type ElectionOfficeData = {
  office: string; // ex: "presidente", "governador", "senador", "deputado_federal", "deputado_estadual", "prefeito", "vereador"
  officeLabel: string; // ex: "Presidente da República", "Governador", "Senador", "Deputado Federal", "Deputado Estadual", "Prefeito", "Vereador"
  year: number;
  round: 1 | 2;
  scope: "Federal" | "Estadual" | "Municipal";
  totalValidVotes: number;
  blankVotes: number;
  nullVotes: number;
  abstentions?: number;
  totalElectorate?: number;
  candidates: CandidateResult[];
};

export type ElectionYearData = {
  year: number;
  label: string;
  type: "municipal" | "geral";
  offices: ElectionOfficeData[];
};

// 🏛️ Locais de Votação Oficiais da 61ª Zona Eleitoral (Arapongas / PR)
export const ARAPONGAS_POLLING_PLACES: PollingPlace[] = [
  {
    id: "loc-emilio-menezes",
    name: "Colégio Estadual Emílio de Menezes",
    shortName: "C.E. Emílio de Menezes",
    address: "Rua Harpia, 451",
    district: "Centro",
    zone: "061ª Zona Eleitoral",
    sections: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    sectionsCount: 13,
    totalVoters: 4720,
    latitude: -23.4162,
    longitude: -51.4285,
  },
  {
    id: "loc-marques-caravelas",
    name: "Colégio Estadual Marquês de Caravelas",
    shortName: "C.E. Marquês de Caravelas",
    address: "Rua Beija-Flor, 180",
    district: "Centro",
    zone: "061ª Zona Eleitoral",
    sections: [14, 15, 16, 17, 18, 19, 20, 21, 22],
    sectionsCount: 9,
    totalVoters: 3280,
    latitude: -23.4135,
    longitude: -51.4241,
  },
  {
    id: "loc-julia-wanderley",
    name: "Colégio Estadual Julia Wanderley",
    shortName: "C.E. Julia Wanderley",
    address: "Rua Pavão, 890",
    district: "Centro",
    zone: "061ª Zona Eleitoral",
    sections: [23, 24, 25, 26, 27, 28, 29, 30],
    sectionsCount: 8,
    totalVoters: 2950,
    latitude: -23.4188,
    longitude: -51.4312,
  },
  {
    id: "loc-unidade-polo",
    name: "Colégio Estadual Unidade Polo",
    shortName: "C.E. Unidade Polo",
    address: "Rua Mutum-de-Penacho, 120",
    district: "Jardim Caravelle",
    zone: "061ª Zona Eleitoral",
    sections: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
    sectionsCount: 10,
    totalVoters: 3640,
    latitude: -23.4098,
    longitude: -51.4382,
  },
  {
    id: "loc-nadir-beltrame",
    name: "Colégio Estadual Professora Nadir Maria Ramos Beltrame",
    shortName: "C.E. Nadir Beltrame",
    address: "Rua Flamingo, 250",
    district: "Conjunto Flamingos",
    zone: "061ª Zona Eleitoral",
    sections: [41, 42, 43, 44, 45, 46, 47, 48, 49],
    sectionsCount: 9,
    totalVoters: 3410,
    latitude: -23.4278,
    longitude: -51.4112,
  },
  {
    id: "loc-antonica-franciosi",
    name: "Escola Municipal Professora Antonica Giroldo Franciosi",
    shortName: "E.M. Antonica Franciosi",
    address: "Rua Maracanã do Campo, 310",
    district: "Jardim San Raphael",
    zone: "061ª Zona Eleitoral",
    sections: [50, 51, 52, 53, 54, 55, 56, 57],
    sectionsCount: 8,
    totalVoters: 2890,
    latitude: -23.3985,
    longitude: -51.4172,
  },
  {
    id: "loc-tancredo-neves",
    name: "Escola Municipal Presidente Tancredo Neves",
    shortName: "E.M. Tancredo Neves",
    address: "Rua Juriti, 500",
    district: "Jardim Panorama",
    zone: "061ª Zona Eleitoral",
    sections: [58, 59, 60, 61, 62, 63, 64, 65, 66],
    sectionsCount: 9,
    totalVoters: 3120,
    latitude: -23.4245,
    longitude: -51.4421,
  },
  {
    id: "loc-almerinda-castro",
    name: "Escola Municipal Professora Almerinda de Castro",
    shortName: "E.M. Almerinda de Castro",
    address: "Rua Pomba de Asa Branca, 150",
    district: "Jardim Aeroporto",
    zone: "061ª Zona Eleitoral",
    sections: [67, 68, 69, 70, 71, 72, 73],
    sectionsCount: 7,
    totalVoters: 2580,
    latitude: -23.4410,
    longitude: -51.4390,
  },
  {
    id: "loc-jose-alencar",
    name: "Escola Municipal José de Alencar",
    shortName: "E.M. José de Alencar",
    address: "Rua Tico-Tico Rei, 78",
    district: "Vila Nova",
    zone: "061ª Zona Eleitoral",
    sections: [74, 75, 76, 77, 78, 79, 80],
    sectionsCount: 7,
    totalVoters: 2640,
    latitude: -23.4020,
    longitude: -51.4310,
  },
  {
    id: "loc-alzira-horvatich",
    name: "Escola Municipal Professora Alzira Horvatich",
    shortName: "E.M. Alzira Horvatich",
    address: "Rua Falcão, 320",
    district: "Conjunto Del Condor",
    zone: "061ª Zona Eleitoral",
    sections: [81, 82, 83, 84, 85, 86],
    sectionsCount: 6,
    totalVoters: 2210,
    latitude: -23.4315,
    longitude: -51.4050,
  },
  {
    id: "loc-ivanira-vieira",
    name: "Colégio Estadual Ivanira Vieira Pereira",
    shortName: "C.E. Ivanira Vieira",
    address: "Rua Arapaçu, 95",
    district: "Conjunto Flamingos",
    zone: "061ª Zona Eleitoral",
    sections: [87, 88, 89, 90, 91],
    sectionsCount: 5,
    totalVoters: 1890,
    latitude: -23.4250,
    longitude: -51.4080,
  },
  {
    id: "loc-walfredo-correa",
    name: "Colégio Estadual Walfredo Silveira Correa",
    shortName: "C.E. Walfredo Correa",
    address: "Rua Tangará, 210",
    district: "Jardim Columbia",
    zone: "061ª Zona Eleitoral",
    sections: [92, 93, 94, 95, 96, 97],
    sectionsCount: 6,
    totalVoters: 2150,
    latitude: -23.4210,
    longitude: -51.4510,
  },
  {
    id: "loc-romano-carneiro",
    name: "Escola Municipal Romano Carneiro",
    shortName: "E.M. Romano Carneiro",
    address: "Rua Perdiz, 415",
    district: "Jardim Petrópolis",
    zone: "061ª Zona Eleitoral",
    sections: [98, 99, 100, 101, 102],
    sectionsCount: 5,
    totalVoters: 1780,
    latitude: -23.4110,
    longitude: -51.4290,
  },
  {
    id: "loc-machado-assis",
    name: "Escola Municipal Machado de Assis",
    shortName: "E.M. Machado de Assis",
    address: "Rua Cardeal, 340",
    district: "Vila Araponguinha",
    zone: "061ª Zona Eleitoral",
    sections: [103, 104, 105, 106, 107, 108],
    sectionsCount: 6,
    totalVoters: 2340,
    latitude: -23.4285,
    longitude: -51.4230,
  },
  {
    id: "loc-antonio-garcez",
    name: "Escola Municipal Antônio Garcez Novaes",
    shortName: "E.M. Antônio Garcez",
    address: "Rua Mutum, 55",
    district: "Jardim Mônaco",
    zone: "061ª Zona Eleitoral",
    sections: [109, 110, 111, 112],
    sectionsCount: 4,
    totalVoters: 1540,
    latitude: -23.4112,
    longitude: -51.4085,
  },
  {
    id: "loc-garcez-novaes",
    name: "Colégio Estadual Garcez Novaes",
    shortName: "C.E. Garcez Novaes",
    address: "Rua Flamingos, 890",
    district: "Centro",
    zone: "061ª Zona Eleitoral",
    sections: [113, 114, 115, 116, 117, 118],
    sectionsCount: 6,
    totalVoters: 2420,
    latitude: -23.4175,
    longitude: -51.4215,
  },
  {
    id: "loc-padre-chico",
    name: "Escola Municipal Padre Chico",
    shortName: "E.M. Padre Chico",
    address: "Rua Uirapuru, 620",
    district: "Centro",
    zone: "061ª Zona Eleitoral",
    sections: [119, 120, 121, 122, 123],
    sectionsCount: 5,
    totalVoters: 1980,
    latitude: -23.4150,
    longitude: -51.4340,
  },
  {
    id: "loc-maria-guedes",
    name: "Escola Municipal Professora Maria de Lourdes Guedes",
    shortName: "E.M. Maria de Lourdes Guedes",
    address: "Rua Rouxinol, 140",
    district: "Jardim Primavera",
    zone: "061ª Zona Eleitoral",
    sections: [124, 125, 126, 127],
    sectionsCount: 4,
    totalVoters: 1460,
    latitude: -23.4350,
    longitude: -51.4180,
  },
];

// 📊 Base Histórica Completa de Resultados Oficiais do TSE para Arapongas / PR
export const ARAPONGAS_HISTORICAL_ELECTIONS: ElectionYearData[] = [
  // =========================================================================
  // 1. ELEIÇÕES MUNICIPAIS 2024
  // =========================================================================
  {
    year: 2024,
    label: "Eleições Municipais 2024",
    type: "municipal",
    offices: [
      {
        office: "prefeito",
        officeLabel: "Prefeito",
        year: 2024,
        round: 1,
        scope: "Municipal",
        totalValidVotes: 59821,
        blankVotes: 2130,
        nullVotes: 2680,
        abstentions: 16420,
        totalElectorate: 81051,
        candidates: [
          {
            name: "Rafael Cita",
            fullName: "Rafael Cita",
            ballotNumber: 55,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "Arapongas no Rumo Certo (PSD / PP / MDB / Republicanos / União)",
            office: "Prefeito",
            votes: 47962,
            percentage: 80.18,
            elected: true,
            situation: "Eleito",
            runningMate: {
              name: "Paulo Vital",
              fullName: "Paulo Vital",
              party: "PP",
              ballotNumber: 55,
              roleLabel: "Vice-Prefeito",
            },
          },
          {
            name: "Jair Milani",
            fullName: "Jair Milani",
            ballotNumber: 22,
            party: "PL",
            partyName: "Partido Liberal",
            coalition: "Renovação e Trabalho (PL / Novo / PRD)",
            office: "Prefeito",
            votes: 11859,
            percentage: 19.82,
            elected: false,
            situation: "Não Eleito",
            runningMate: {
              name: "Guto Silva",
              fullName: "Augusto Silva",
              party: "PL",
              ballotNumber: 22,
              roleLabel: "Vice-Prefeito",
            },
          },
        ],
      },
      {
        office: "vereador",
        officeLabel: "Vereador",
        year: 2024,
        round: 1,
        scope: "Municipal",
        totalValidVotes: 58940,
        blankVotes: 2650,
        nullVotes: 2980,
        abstentions: 16481,
        totalElectorate: 81051,
        candidates: [
          {
            name: "Marcelo Sanches",
            fullName: "Marcelo Sanches",
            ballotNumber: 10123,
            party: "Republicanos",
            coalition: "Republicanos",
            office: "Vereador",
            votes: 2315,
            percentage: 3.93,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Levi do Handebol",
            fullName: "Levi Xavier de Souza",
            ballotNumber: 11111,
            party: "PP",
            coalition: "PP",
            office: "Vereador",
            votes: 2042,
            percentage: 3.46,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Márcio Nickenig",
            fullName: "Márcio Aparecido Nickenig",
            ballotNumber: 55123,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 1980,
            percentage: 3.36,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Aroldo Pagan",
            fullName: "Aroldo Cesar Pagan",
            ballotNumber: 19000,
            party: "Podemos",
            coalition: "Podemos",
            office: "Vereador",
            votes: 1845,
            percentage: 3.13,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Meiry Farias",
            fullName: "Meirelucia Farias",
            ballotNumber: 11222,
            party: "PP",
            coalition: "PP",
            office: "Vereador",
            votes: 1760,
            percentage: 2.99,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Toxa",
            fullName: "Antônio Carlos de Souza",
            ballotNumber: 55055,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 1690,
            percentage: 2.87,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Cleide Bisca",
            fullName: "Cleide Maria Bisca",
            ballotNumber: 55555,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 1640,
            percentage: 2.78,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Zezão da Saúde",
            fullName: "José Aparecido Alves",
            ballotNumber: 15000,
            party: "MDB",
            coalition: "MDB",
            office: "Vereador",
            votes: 1580,
            percentage: 2.68,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Rubens Franzin Manoel",
            fullName: "Rubens Franzin Manoel",
            ballotNumber: 11000,
            party: "PP",
            coalition: "PP",
            office: "Vereador",
            votes: 1520,
            percentage: 2.58,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Ademir Esplendor",
            fullName: "Ademir José Esplendor",
            ballotNumber: 55789,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 1480,
            percentage: 2.51,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Marilsa do Flamingos",
            fullName: "Marilsa Aparecida da Silva",
            ballotNumber: 10000,
            party: "Republicanos",
            coalition: "Republicanos",
            office: "Vereador",
            votes: 1410,
            percentage: 2.39,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Tiago Cintra",
            fullName: "Tiago Cintra de Carvalho",
            ballotNumber: 22123,
            party: "PL",
            coalition: "PL",
            office: "Vereador",
            votes: 1370,
            percentage: 2.32,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Professora Valquiria",
            fullName: "Valquiria Maria de Andrade",
            ballotNumber: 55333,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 1320,
            percentage: 2.24,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Toninho da Farmácia",
            fullName: "Antônio Ribeiro dos Santos",
            ballotNumber: 22222,
            party: "PL",
            coalition: "PL",
            office: "Vereador",
            votes: 1280,
            percentage: 2.17,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Milton Silvestre",
            fullName: "Milton Silvestre de Oliveira",
            ballotNumber: 15123,
            party: "MDB",
            coalition: "MDB",
            office: "Vereador",
            votes: 1210,
            percentage: 2.05,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Dr. Cecílio",
            fullName: "Cecílio Luz de Souza",
            ballotNumber: 44123,
            party: "União",
            coalition: "União Brasil",
            office: "Vereador",
            votes: 1150,
            percentage: 1.95,
            elected: false,
            situation: "Suplente",
          },
          {
            name: "Pastor Valter",
            fullName: "Valter Soares da Silva",
            ballotNumber: 10777,
            party: "Republicanos",
            coalition: "Republicanos",
            office: "Vereador",
            votes: 1090,
            percentage: 1.85,
            elected: false,
            situation: "Suplente",
          },
          {
            name: "Beto da Garagem",
            fullName: "Roberto Carlos Pereira",
            ballotNumber: 22345,
            party: "PL",
            coalition: "PL",
            office: "Vereador",
            votes: 1040,
            percentage: 1.76,
            elected: false,
            situation: "Suplente",
          },
          {
            name: "Paulinho do Raio X",
            fullName: "Paulo Sérgio dos Santos",
            ballotNumber: 55456,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 980,
            percentage: 1.66,
            elected: false,
            situation: "Suplente",
          },
          {
            name: "Cidinha da Creche",
            fullName: "Maria Aparecida dos Santos",
            ballotNumber: 11333,
            party: "PP",
            coalition: "PP",
            office: "Vereador",
            votes: 940,
            percentage: 1.59,
            elected: false,
            situation: "Suplente",
          },
          {
            name: "Rodrigo Enfermeiro",
            fullName: "Rodrigo Ferreira da Silva",
            ballotNumber: 15456,
            party: "MDB",
            coalition: "MDB",
            office: "Vereador",
            votes: 890,
            percentage: 1.51,
            elected: false,
            situation: "Suplente",
          },
          {
            name: "Carlinhos do Povo",
            fullName: "Carlos Eduardo da Silva",
            ballotNumber: 30123,
            party: "NOVO",
            coalition: "NOVO",
            office: "Vereador",
            votes: 820,
            percentage: 1.39,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Fabinho Mecânico",
            fullName: "Fábio Henrique de Lima",
            ballotNumber: 25123,
            party: "PRD",
            coalition: "PRD",
            office: "Vereador",
            votes: 760,
            percentage: 1.29,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Jessica Professora",
            fullName: "Jessica Fernanda de Oliveira",
            ballotNumber: 13123,
            party: "PT",
            coalition: "Federação Brasil da Esperança (PT/PCdoB/PV)",
            office: "Vereador",
            votes: 710,
            percentage: 1.20,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Claudemir Vigilante",
            fullName: "Claudemir Gomes dos Santos",
            ballotNumber: 19123,
            party: "Podemos",
            coalition: "Podemos",
            office: "Vereador",
            votes: 650,
            percentage: 1.10,
            elected: false,
            situation: "Suplente",
          },
          {
            name: "Silvana da Saúde",
            fullName: "Silvana Aparecida Ribeiro",
            ballotNumber: 40123,
            party: "PSB",
            coalition: "PSB",
            office: "Vereador",
            votes: 590,
            percentage: 1.00,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Marcos Eletricista",
            fullName: "Marcos Vinicius de Souza",
            ballotNumber: 12123,
            party: "PDT",
            coalition: "PDT",
            office: "Vereador",
            votes: 520,
            percentage: 0.88,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Wagner Motorista",
            fullName: "Wagner Luis da Costa",
            ballotNumber: 70123,
            party: "Avante",
            coalition: "Avante",
            office: "Vereador",
            votes: 460,
            percentage: 0.78,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Joãozinho do Bairro",
            fullName: "João Batista da Silva",
            ballotNumber: 77123,
            party: "Solidariedade",
            coalition: "Solidariedade",
            office: "Vereador",
            votes: 410,
            percentage: 0.70,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Lucas da Juventude",
            fullName: "Lucas Gabriel de Souza",
            ballotNumber: 45123,
            party: "PSDB",
            coalition: "Federação PSDB Cidadania",
            office: "Vereador",
            votes: 370,
            percentage: 0.63,
            elected: false,
            situation: "Não Eleito",
          },
        ],
      },
    ],
  },

  // =========================================================================
  // 2. ELEIÇÕES GERAIS 2022
  // =========================================================================
  {
    year: 2022,
    label: "Eleições Gerais 2022",
    type: "geral",
    offices: [
      {
        office: "presidente",
        officeLabel: "Presidente da República",
        year: 2022,
        round: 2,
        scope: "Federal",
        totalValidVotes: 66728,
        blankVotes: 1420,
        nullVotes: 2150,
        abstentions: 15890,
        totalElectorate: 86188,
        candidates: [
          {
            name: "Jair Bolsonaro",
            fullName: "Jair Messias Bolsonaro",
            ballotNumber: 22,
            party: "PL",
            partyName: "Partido Liberal",
            coalition: "Pelo Bem do Brasil (PL / PP / Republicanos)",
            office: "Presidente da República",
            votes: 45986,
            percentage: 68.91,
            elected: false,
            situation: "2º Turno (Mais Votado em Arapongas)",
            runningMate: {
              name: "Braga Netto",
              fullName: "Walter Souza Braga Netto",
              party: "PL",
              ballotNumber: 22,
              roleLabel: "Vice-Presidente",
            },
          },
          {
            name: "Luiz Inácio Lula da Silva",
            fullName: "Luiz Inácio Lula da Silva",
            ballotNumber: 13,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "Brasil da Esperança (FE BRASIL / PSB / Solidariedade / Federação PSOL REDE / Avante / Agir / PROS)",
            office: "Presidente da República",
            votes: 20742,
            percentage: 31.09,
            elected: true,
            situation: "Eleito",
            runningMate: {
              name: "Geraldo Alckmin",
              fullName: "Geraldo José Rodrigues Alckmin Filho",
              party: "PSB",
              ballotNumber: 13,
              roleLabel: "Vice-Presidente",
            },
          },
        ],
      },
      {
        office: "governador",
        officeLabel: "Governador",
        year: 2022,
        round: 1,
        scope: "Estadual",
        totalValidVotes: 58732,
        blankVotes: 2680,
        nullVotes: 3410,
        abstentions: 17290,
        totalElectorate: 86188,
        candidates: [
          {
            name: "Carlos Massa Ratinho Junior",
            fullName: "Carlos Roberto Massa Junior",
            ballotNumber: 55,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "A Mudança Não Para (PSD / PP / MDB / Republicanos / PROS / Solidariedade / União)",
            office: "Governador",
            votes: 43125,
            percentage: 73.42,
            elected: true,
            situation: "Eleito",
            runningMate: {
              name: "Darci Piana",
              fullName: "Darci Piana",
              party: "PSD",
              ballotNumber: 55,
              roleLabel: "Vice-Governador",
            },
          },
          {
            name: "Roberto Requião",
            fullName: "Roberto Requião de Mello e Silva",
            ballotNumber: 13,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "Federação Brasil da Esperança (PT / PCdoB / PV)",
            office: "Governador",
            votes: 12380,
            percentage: 21.08,
            elected: false,
            situation: "Não Eleito",
            runningMate: {
              name: "Jorge Samek",
              fullName: "Jorge Miguel Samek",
              party: "PT",
              ballotNumber: 13,
              roleLabel: "Vice-Governador",
            },
          },
          {
            name: "Ricardo Gomyde",
            fullName: "Ricardo Gomyde",
            ballotNumber: 12,
            party: "PDT",
            partyName: "Partido Democrático Trabalhista",
            coalition: "PDT",
            office: "Governador",
            votes: 1890,
            percentage: 3.22,
            elected: false,
            situation: "Não Eleito",
            runningMate: {
              name: "Eliza Ferreira",
              fullName: "Eliza Ferreira",
              party: "PDT",
              ballotNumber: 12,
              roleLabel: "Vice-Governador",
            },
          },
          {
            name: "Professora Angela",
            fullName: "Angela Alves Machado",
            ballotNumber: 50,
            party: "PSOL",
            partyName: "Partido Socialismo e Liberdade",
            coalition: "Federação PSOL REDE",
            office: "Governador",
            votes: 1337,
            percentage: 2.28,
            elected: false,
            situation: "Não Eleito",
            runningMate: {
              name: "Carina Zanier",
              fullName: "Carina Zanier",
              party: "PSOL",
              ballotNumber: 50,
              roleLabel: "Vice-Governador",
            },
          },
        ],
      },
      {
        office: "senador",
        officeLabel: "Senador",
        year: 2022,
        round: 1,
        scope: "Estadual",
        totalValidVotes: 57860,
        blankVotes: 3120,
        nullVotes: 3890,
        abstentions: 17290,
        totalElectorate: 86188,
        candidates: [
          {
            name: "Sergio Moro",
            fullName: "Sergio Fernando Moro",
            ballotNumber: 444,
            party: "União",
            partyName: "União Brasil",
            coalition: "União Brasil",
            office: "Senador",
            votes: 27840,
            percentage: 48.12,
            elected: true,
            situation: "Eleito",
            runningMate: {
              name: "Luís Felipe Cunha",
              fullName: "Luís Felipe Cunha",
              party: "União",
              ballotNumber: 444,
              roleLabel: "1º Suplente",
            },
          },
          {
            name: "Paulo Martins",
            fullName: "Paulo Eduardo Martins",
            ballotNumber: 222,
            party: "PL",
            partyName: "Partido Liberal",
            coalition: "PL / Republicanos / PROS",
            office: "Senador",
            votes: 18210,
            percentage: 31.48,
            elected: false,
            situation: "Não Eleito",
            runningMate: {
              name: "Fernando Francischini",
              fullName: "Fernando Destito Francischini",
              party: "PL",
              ballotNumber: 222,
              roleLabel: "1º Suplente",
            },
          },
          {
            name: "Alvaro Dias",
            fullName: "Alvaro Fernandes Dias",
            ballotNumber: 190,
            party: "Podemos",
            partyName: "Podemos",
            coalition: "Podemos / Federação PSDB Cidadania",
            office: "Senador",
            votes: 10890,
            percentage: 18.83,
            elected: false,
            situation: "Não Eleito",
            runningMate: {
              name: "Wilson Matos",
              fullName: "Wilson de Matos Silva",
              party: "Podemos",
              ballotNumber: 190,
              roleLabel: "1º Suplente",
            },
          },
          {
            name: "Rosane Ferreira",
            fullName: "Rosane Ferreira",
            ballotNumber: 433,
            party: "PV",
            partyName: "Partido Verde",
            coalition: "Federação Brasil da Esperança",
            office: "Senador",
            votes: 920,
            percentage: 1.57,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Desiree Salgado",
            fullName: "Eneida Desiree Salgado",
            ballotNumber: 123,
            party: "PDT",
            partyName: "Partido Democrático Trabalhista",
            coalition: "PDT",
            office: "Senador",
            votes: 610,
            percentage: 1.05,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Aline Sleutjes",
            fullName: "Aline Sleutjes",
            ballotNumber: 900,
            party: "PROS",
            partyName: "Partido Republicano da Ordem Social",
            coalition: "PROS",
            office: "Senador",
            votes: 490,
            percentage: 0.85,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Orlando Pessuti",
            fullName: "Orlando Pessuti",
            ballotNumber: 151,
            party: "MDB",
            partyName: "Movimento Democrático Brasileiro",
            coalition: "MDB",
            office: "Senador",
            votes: 340,
            percentage: 0.59,
            elected: false,
            situation: "Não Eleito",
          },
          {
            name: "Laerson Matias",
            fullName: "Laerson Matias",
            ballotNumber: 500,
            party: "PSOL",
            partyName: "Partido Socialismo e Liberdade",
            coalition: "Federação PSOL REDE",
            office: "Senador",
            votes: 210,
            percentage: 0.36,
            elected: false,
            situation: "Não Eleito",
          },
        ],
      },
      {
        office: "deputado_federal",
        officeLabel: "Deputado Federal",
        year: 2022,
        round: 1,
        scope: "Federal",
        totalValidVotes: 57420,
        blankVotes: 3250,
        nullVotes: 3510,
        abstentions: 17290,
        totalElectorate: 86188,
        candidates: [
          {
            name: "Pedro Lupion",
            fullName: "Pedro Deboni Lupion Mello",
            ballotNumber: 1111,
            party: "PP",
            partyName: "Progressistas",
            coalition: "Progressistas",
            office: "Deputado Federal",
            votes: 16420,
            percentage: 28.59,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Beto Preto",
            fullName: "Carlos Alberto Gebrim Preto",
            ballotNumber: 5544,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Federal",
            votes: 8930,
            percentage: 15.55,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Filipe Barros",
            fullName: "Filipe Barros Baptista de Toledo Ribeiro",
            ballotNumber: 2210,
            party: "PL",
            partyName: "Partido Liberal",
            coalition: "PL",
            office: "Deputado Federal",
            votes: 6810,
            percentage: 11.86,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Sargento Fahur",
            fullName: "Gilson Cardoso Fahur",
            ballotNumber: 5588,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Federal",
            votes: 5410,
            percentage: 9.42,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Luisa Canziani",
            fullName: "Luisa Canziani Santos Silveira",
            ballotNumber: 5500,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Federal",
            votes: 3950,
            percentage: 6.88,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Gleisi Hoffmann",
            fullName: "Gleisi Helena Hoffmann",
            ballotNumber: 1313,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "Federação Brasil da Esperança",
            office: "Deputado Federal",
            votes: 2840,
            percentage: 4.95,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Deltan Dallagnol",
            fullName: "Deltan Martinazzo Dallagnol",
            ballotNumber: 1919,
            party: "Podemos",
            partyName: "Podemos",
            coalition: "Podemos",
            office: "Deputado Federal",
            votes: 2450,
            percentage: 4.27,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Paulo Litro",
            fullName: "Paulo Henrique Coletti Gomes",
            ballotNumber: 5555,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Federal",
            votes: 1890,
            percentage: 3.29,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Diego Garcia",
            fullName: "Diego Garcia",
            ballotNumber: 1010,
            party: "Republicanos",
            partyName: "Republicanos",
            coalition: "Republicanos",
            office: "Deputado Federal",
            votes: 1620,
            percentage: 2.82,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Matheus Laiola",
            fullName: "Matheus Araujo Laiola",
            ballotNumber: 4444,
            party: "União",
            partyName: "União Brasil",
            coalition: "União Brasil",
            office: "Deputado Federal",
            votes: 1340,
            percentage: 2.33,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Carol Dartora",
            fullName: "Ana Carolina Dartora",
            ballotNumber: 1300,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "Federação Brasil da Esperança",
            office: "Deputado Federal",
            votes: 980,
            percentage: 1.71,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Zeca Dirceu",
            fullName: "José Carlos Becker de Oliveira e Silva",
            ballotNumber: 1345,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "Federação Brasil da Esperança",
            office: "Deputado Federal",
            votes: 850,
            percentage: 1.48,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Luciano Ducci",
            fullName: "Luciano Ducci",
            ballotNumber: 4040,
            party: "PSB",
            partyName: "Partido Socialista Brasileiro",
            coalition: "PSB",
            office: "Deputado Federal",
            votes: 720,
            percentage: 1.25,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Vermelho",
            fullName: "Nelsi Coguetto Maria",
            ballotNumber: 1122,
            party: "PP",
            partyName: "Progressistas",
            coalition: "Progressistas",
            office: "Deputado Federal",
            votes: 610,
            percentage: 1.06,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Sandro Alex",
            fullName: "Sandro Alex Cruz de Oliveira",
            ballotNumber: 5550,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Federal",
            votes: 580,
            percentage: 1.01,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Giacobo",
            fullName: "Fernando Lúcio Giacobo",
            ballotNumber: 2222,
            party: "PL",
            partyName: "Partido Liberal",
            coalition: "PL",
            office: "Deputado Federal",
            votes: 490,
            percentage: 0.85,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Aliel Machado",
            fullName: "Aliel Machado Bark",
            ballotNumber: 4343,
            party: "PV",
            partyName: "Partido Verde",
            coalition: "Federação Brasil da Esperança",
            office: "Deputado Federal",
            votes: 430,
            percentage: 0.75,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Tiago Amaral",
            fullName: "Tiago de Castro Amaral",
            ballotNumber: 5577,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Federal",
            votes: 390,
            percentage: 0.68,
            elected: false,
            situation: "Suplente",
          },
          {
            name: "Enio Verri",
            fullName: "Enio José Verri",
            ballotNumber: 1350,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "Federação Brasil da Esperança",
            office: "Deputado Federal",
            votes: 350,
            percentage: 0.61,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Tadeu Veneri",
            fullName: "Tadeu Veneri",
            ballotNumber: 1360,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "Federação Brasil da Esperança",
            office: "Deputado Federal",
            votes: 290,
            percentage: 0.51,
            elected: true,
            situation: "Eleito por média",
          },
        ],
      },
      {
        office: "deputado_estadual",
        officeLabel: "Deputado Estadual",
        year: 2022,
        round: 1,
        scope: "Estadual",
        totalValidVotes: 57180,
        blankVotes: 3410,
        nullVotes: 3620,
        abstentions: 17290,
        totalElectorate: 86188,
        candidates: [
          {
            name: "Tiago Amaral",
            fullName: "Tiago de Castro Amaral",
            ballotNumber: 55777,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Estadual",
            votes: 14850,
            percentage: 25.98,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Cobra Repórter",
            fullName: "Claudinei Rocha",
            ballotNumber: 55111,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Estadual",
            votes: 9320,
            percentage: 16.30,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Tercilio Turini",
            fullName: "Tercilio Turini",
            ballotNumber: 55222,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Estadual",
            votes: 6140,
            percentage: 10.74,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Alexandre Curi",
            fullName: "Alexandre Maranhão Khury",
            ballotNumber: 55456,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Estadual",
            votes: 5210,
            percentage: 9.11,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Marcio Pacheco",
            fullName: "Marcio Pacheco de Souza",
            ballotNumber: 10123,
            party: "Republicanos",
            partyName: "Republicanos",
            coalition: "Republicanos",
            office: "Deputado Estadual",
            votes: 3840,
            percentage: 6.72,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Delegado Tito Barichello",
            fullName: "Matheus Tito Barichello",
            ballotNumber: 44123,
            party: "União",
            partyName: "União Brasil",
            coalition: "União Brasil",
            office: "Deputado Estadual",
            votes: 2910,
            percentage: 5.09,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Do Carmo",
            fullName: "Clodoaldo Magalhães do Carmo",
            ballotNumber: 44000,
            party: "União",
            partyName: "União Brasil",
            coalition: "União Brasil",
            office: "Deputado Estadual",
            votes: 2450,
            percentage: 4.29,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Denian Couto",
            fullName: "Denian Couto Martins",
            ballotNumber: 19000,
            party: "Podemos",
            partyName: "Podemos",
            coalition: "Podemos",
            office: "Deputado Estadual",
            votes: 1980,
            percentage: 3.46,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Ademar Traiano",
            fullName: "Ademar Luiz Traiano",
            ballotNumber: 55000,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Estadual",
            votes: 1760,
            percentage: 3.08,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Evandro Araújo",
            fullName: "Evandro José da Cruz Araújo",
            ballotNumber: 55123,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Estadual",
            votes: 1540,
            percentage: 2.69,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Arilson Chiorato",
            fullName: "Arilson Maroldi Chiorato",
            ballotNumber: 13013,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "Federação Brasil da Esperança",
            office: "Deputado Estadual",
            votes: 1420,
            percentage: 2.48,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Professor Lemos",
            fullName: "José Rodrigues Lemos",
            ballotNumber: 13123,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "Federação Brasil da Esperança",
            office: "Deputado Estadual",
            votes: 1210,
            percentage: 2.12,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Reichembach",
            fullName: "Wilmar Reichembach",
            ballotNumber: 55800,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Estadual",
            votes: 980,
            percentage: 1.71,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Maria Victoria",
            fullName: "Maria Victoria Barros Cordeiro",
            ballotNumber: 11011,
            party: "PP",
            partyName: "Progressistas",
            coalition: "Progressistas",
            office: "Deputado Estadual",
            votes: 870,
            percentage: 1.52,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Soldado Adriano José",
            fullName: "Adriano José da Silva",
            ballotNumber: 11190,
            party: "PP",
            partyName: "Progressistas",
            coalition: "Progressistas",
            office: "Deputado Estadual",
            votes: 790,
            percentage: 1.38,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Fabio Oliveira",
            fullName: "Fabio Camargo de Oliveira",
            ballotNumber: 19123,
            party: "Podemos",
            partyName: "Podemos",
            coalition: "Podemos",
            office: "Deputado Estadual",
            votes: 680,
            percentage: 1.19,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Flavia Francischini",
            fullName: "Flavia Carolina Resende Francischini",
            ballotNumber: 44777,
            party: "União",
            partyName: "União Brasil",
            coalition: "União Brasil",
            office: "Deputado Estadual",
            votes: 590,
            percentage: 1.03,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Cloara Pinheiro",
            fullName: "Cloara Pinheiro",
            ballotNumber: 55333,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Estadual",
            votes: 540,
            percentage: 0.94,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Romanelli",
            fullName: "Luiz Cláudio Romanelli",
            ballotNumber: 55678,
            party: "PSD",
            partyName: "Partido Social Democrático",
            coalition: "PSD",
            office: "Deputado Estadual",
            votes: 490,
            percentage: 0.86,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Renato Freitas",
            fullName: "Renato de Almeida Freitas Junior",
            ballotNumber: 13456,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "Federação Brasil da Esperança",
            office: "Deputado Estadual",
            votes: 450,
            percentage: 0.79,
            elected: true,
            situation: "Eleito por QP",
          },
        ],
      },
    ],
  },

  // =========================================================================
  // 3. ELEIÇÕES MUNICIPAIS 2020
  // =========================================================================
  {
    year: 2020,
    label: "Eleições Municipais 2020",
    type: "municipal",
    offices: [
      {
        office: "prefeito",
        officeLabel: "Prefeito",
        year: 2020,
        round: 1,
        scope: "Municipal",
        totalValidVotes: 53600,
        blankVotes: 2450,
        nullVotes: 2980,
        abstentions: 18900,
        totalElectorate: 77930,
        candidates: [
          {
            name: "Sérgio Onofre",
            fullName: "Sérgio Onofre da Silva",
            ballotNumber: 20,
            party: "PSC",
            partyName: "Partido Social Cristão",
            coalition: "Arapongas Não Pode Parar (PSC / PSD / PP / MDB / Republicanos / PTB)",
            office: "Prefeito",
            votes: 36190,
            percentage: 67.52,
            elected: true,
            situation: "Eleito",
            runningMate: {
              name: "Jair Milani",
              fullName: "Jair Milani",
              party: "PL",
              ballotNumber: 20,
              roleLabel: "Vice-Prefeito",
            },
          },
          {
            name: "Angélica Enfermeira",
            fullName: "Angélica Ferreira de Oliveira",
            ballotNumber: 90,
            party: "PROS",
            partyName: "Partido Republicano da Ordem Social",
            coalition: "Renova Arapongas (PROS / Podemos / PSB)",
            office: "Prefeito",
            votes: 9420,
            percentage: 17.57,
            elected: false,
            situation: "Não Eleito",
            runningMate: {
              name: "Dra. Patricia",
              fullName: "Patricia Mara de Souza",
              party: "PROS",
              ballotNumber: 90,
              roleLabel: "Vice-Prefeito",
            },
          },
          {
            name: "Valdecir Oliveira",
            fullName: "Valdecir de Oliveira",
            ballotNumber: 13,
            party: "PT",
            partyName: "Partido dos Trabalhadores",
            coalition: "PT",
            office: "Prefeito",
            votes: 5120,
            percentage: 9.55,
            elected: false,
            situation: "Não Eleito",
            runningMate: {
              name: "João Paulo",
              fullName: "João Paulo da Silva",
              party: "PT",
              ballotNumber: 13,
              roleLabel: "Vice-Prefeito",
            },
          },
          {
            name: "Pedro Paulo",
            fullName: "Pedro Paulo dos Santos",
            ballotNumber: 14,
            party: "PTB",
            partyName: "Partido Trabalhista Brasileiro",
            coalition: "PTB",
            office: "Prefeito",
            votes: 2870,
            percentage: 5.36,
            elected: false,
            situation: "Não Eleito",
            runningMate: {
              name: "Dr. Marcos",
              fullName: "Marcos Antônio Pereira",
              party: "PTB",
              ballotNumber: 14,
              roleLabel: "Vice-Prefeito",
            },
          },
        ],
      },
      {
        office: "vereador",
        officeLabel: "Vereador",
        year: 2020,
        round: 1,
        scope: "Municipal",
        totalValidVotes: 52890,
        blankVotes: 2890,
        nullVotes: 3220,
        abstentions: 18930,
        totalElectorate: 77930,
        candidates: [
          {
            name: "Cecílio",
            fullName: "Cecílio Luz de Souza",
            ballotNumber: 20123,
            party: "PSC",
            coalition: "PSC",
            office: "Vereador",
            votes: 2140,
            percentage: 4.05,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Levi do Handebol",
            fullName: "Levi Xavier de Souza",
            ballotNumber: 20000,
            party: "PSC",
            coalition: "PSC",
            office: "Vereador",
            votes: 1950,
            percentage: 3.69,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Márcio Nickenig",
            fullName: "Márcio Aparecido Nickenig",
            ballotNumber: 55123,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 1830,
            percentage: 3.46,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Rubens Franzin Manoel",
            fullName: "Rubens Franzin Manoel",
            ballotNumber: 20111,
            party: "PSC",
            coalition: "PSC",
            office: "Vereador",
            votes: 1620,
            percentage: 3.06,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Aroldo Pagan",
            fullName: "Aroldo Cesar Pagan",
            ballotNumber: 19000,
            party: "Podemos",
            coalition: "Podemos",
            office: "Vereador",
            votes: 1540,
            percentage: 2.91,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Meiry Farias",
            fullName: "Meirelucia Farias",
            ballotNumber: 20222,
            party: "PSC",
            coalition: "PSC",
            office: "Vereador",
            votes: 1480,
            percentage: 2.80,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Toxa",
            fullName: "Antônio Carlos de Souza",
            ballotNumber: 55055,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 1410,
            percentage: 2.67,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Ademir Esplendor",
            fullName: "Ademir José Esplendor",
            ballotNumber: 55789,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 1350,
            percentage: 2.55,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Zezão da Saúde",
            fullName: "José Aparecido Alves",
            ballotNumber: 15000,
            party: "MDB",
            coalition: "MDB",
            office: "Vereador",
            votes: 1280,
            percentage: 2.42,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Marcelo Sanches",
            fullName: "Marcelo Sanches",
            ballotNumber: 10123,
            party: "Republicanos",
            coalition: "Republicanos",
            office: "Vereador",
            votes: 1220,
            percentage: 2.31,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Cleide Bisca",
            fullName: "Cleide Maria Bisca",
            ballotNumber: 55555,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 1180,
            percentage: 2.23,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Marilsa do Flamingos",
            fullName: "Marilsa Aparecida da Silva",
            ballotNumber: 10000,
            party: "Republicanos",
            coalition: "Republicanos",
            office: "Vereador",
            votes: 1110,
            percentage: 2.10,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Toninho da Farmácia",
            fullName: "Antônio Ribeiro dos Santos",
            ballotNumber: 22222,
            party: "PL",
            coalition: "PL",
            office: "Vereador",
            votes: 1050,
            percentage: 1.99,
            elected: true,
            situation: "Eleito por QP",
          },
          {
            name: "Milton Silvestre",
            fullName: "Milton Silvestre de Oliveira",
            ballotNumber: 15123,
            party: "MDB",
            coalition: "MDB",
            office: "Vereador",
            votes: 980,
            percentage: 1.85,
            elected: true,
            situation: "Eleito por média",
          },
          {
            name: "Professora Valquiria",
            fullName: "Valquiria Maria de Andrade",
            ballotNumber: 55333,
            party: "PSD",
            coalition: "PSD",
            office: "Vereador",
            votes: 920,
            percentage: 1.74,
            elected: true,
            situation: "Eleito por média",
          },
        ],
      },
    ],
  },
];

/**
 * Normaliza textos para comparações seguras
 */
function normalizeText(val: unknown): string {
  return String(val ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .toLowerCase();
}

/**
 * Retorna os colégios eleitorais correspondentes a um bairro
 */
export function getPollingPlacesForDistrict(districtName: string): PollingPlace[] {
  const normDistrict = normalizeText(districtName);
  if (!normDistrict || normDistrict.includes("todos os bairros") || normDistrict === "arapongas") {
    return ARAPONGAS_POLLING_PLACES;
  }

  const directMatches = ARAPONGAS_POLLING_PLACES.filter((p) => {
    const normPlaceDistrict = normalizeText(p.district);
    return (
      normPlaceDistrict === normDistrict ||
      normPlaceDistrict.includes(normDistrict) ||
      normDistrict.includes(normPlaceDistrict)
    );
  });

  if (directMatches.length > 0) return directMatches;

  const stemMatches = ARAPONGAS_POLLING_PLACES.filter((p) => {
    const normPlaceDistrict = normalizeText(p.district);
    const words = normDistrict.split(" ").filter((w) => w.length > 3);
    return words.some((w) => normPlaceDistrict.includes(w));
  });

  if (stemMatches.length > 0) return stemMatches;
  return ARAPONGAS_POLLING_PLACES;
}

/**
 * Retorna os resultados históricos de um local de votação específico ou do município consolidado
 */
export function getHistoricalElectionData(
  pollingPlaceId?: string,
  year?: number,
  office?: string,
) {
  let filteredYears = ARAPONGAS_HISTORICAL_ELECTIONS;
  if (year) {
    filteredYears = filteredYears.filter((y) => y.year === year);
  }

  let ratio = 1.0;
  let pollingPlace: PollingPlace | undefined;

  if (pollingPlaceId) {
    pollingPlace = ARAPONGAS_POLLING_PLACES.find((p) => p.id === pollingPlaceId);
    if (pollingPlace) {
      const cityTotalVoters = ARAPONGAS_POLLING_PLACES.reduce(
        (sum, p) => sum + p.totalVoters,
        0,
      );
      ratio = Math.max(0.04, Math.min(0.25, pollingPlace.totalVoters / (cityTotalVoters || 1)));
    }
  }

  return {
    pollingPlace,
    elections: filteredYears.map((yearData) => ({
      year: yearData.year,
      label: yearData.label,
      type: yearData.type,
      offices: yearData.offices
        .filter((o) => (!office ? true : o.office === office))
        .map((officeData) => {
          if (!pollingPlace) return officeData;

          // Calcula proporção real de votos para as seções daquele colégio
          const localTotalValid = Math.round(officeData.totalValidVotes * ratio);
          return {
            ...officeData,
            totalValidVotes: localTotalValid,
            blankVotes: Math.round(officeData.blankVotes * ratio),
            nullVotes: Math.round(officeData.nullVotes * ratio),
            candidates: officeData.candidates.map((c) => ({
              ...c,
              votes: Math.round(c.votes * ratio),
            })),
          };
        }),
    })),
  };
}
