import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AdaptivePerformance from "./adaptive-performance";
import SignupMunicipalityEnhancer from "./signup-municipality-enhancer";
import DashboardRuntimeEnhancers from "./dashboard-runtime-enhancers";
import DashboardRouteViewEnhancer from "./dashboard-route-view-enhancer";
import PwaInstaller from "./pwa-installer";
import "./globals.css";
import "./optimized-dashboard.css";
import "./contatos/coverage-clarity.css";
import "./contatos/contact-quality-label.css";
import "./contatos/whatsapp-quick-queue.css";
import "./contatos/contacts-ux.css";
import "./contatos/hide-meetings-kpi.css";
import "./contatos/contacts-full-theme.css";
import "./contatos/contacts-mobile-polish.css";
import "./contatos/mobile-contact-row-accordion.css";
import "./contacts-official-shell-bridge.css";
import "./contacts-stability.css";
import "./compact-overview-scope.css";
import "./neighborhood-info-drawer.css";
import "./map-neighborhood-permissions.css";
import "./system-notifications.css";
import "./whaticket-broadcast.css";
import "./adaptive-performance.css";
import "./mobile-map-cleanup.css";
import "./mobile-analytics-controls.css";
import "./map-layout-compact.css";
import "./safe-map-contact-tools.css";
import "./map-territory-enhancer.css";
import "./map-geocoding-panel.css";
import "./map-district-filter.css";
import "./map-heatmap-enhancer.css";
import "./map-district-summary.css";
import "./map-priority-panel.css";
import "./map-strategy-insights.css";
import "./executive-dashboard.css";
import "./data-quality-panel.css";
import "./user-hierarchy.css";
import "./team-performance-admin-enhancer.css";
import "./auth-reconciliation.css";
import "./account-settings.css";
import "./account-session-security.css";
import "./sidebar-scroll-fix.css";
import "./contact-export-history.css";
import "./municipality-multitenant.css";
import "./municipality-management.css";
import "./gestor-access-ui.css";
import "./runtime-version-guard.css";
import "./ux-audit-fixes.css";
import "./voto-forte-unified-theme.css";
import "./theme-toggle-global.css";
import "./topbar-theme-sync.css";
import "./remove-electoral-back-system.css";
import "./agenda-mobile-compact.css";
import "./agenda-mobile-direct-fix.css";
import "./agenda-mobile-scroll-root-fix.css";
import "./profile-modal-exact.css";
import "./map-mobile-visual-polish.css";
import "./map-mobile-theme-contrast.css";
import "./map-mobile-contacts-panel-theme.css";
import "./map-mobile-compact-experience.css";
import "./overview-mobile-visual-polish.css";
import "./overview-mobile-header-final.css";
import "./overview-mobile-density-fix.css";
import "./map-mobile-header-compact.css";
import "./mobile-tab-header-standard.css";
import "./primary-mobile-header-standard.css";
import "./dark-only-header-alignment.css";
import "./mobile-overview-loading.css";
import "./agenda-mobile-scroll-priority.css";
import "./contacts-final-mobile-stability.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const THEME_BOOTSTRAP_SCRIPT = `(function(){document.documentElement.dataset.vfTheme='dark';document.documentElement.style.colorScheme='dark';})();`;
export const viewport: Viewport = { width:"device-width", initialScale:1, maximumScale:1, userScalable:false, viewportFit:"cover", themeColor:"#051929" };
export const metadata: Metadata = { title:"VOTO FORTE PARANÁ", description:"Gestão inteligente de campanha em todo o Paraná.", manifest:"/manifest.json", appleWebApp:{capable:true,statusBarStyle:"black-translucent",title:"VOTO FORTE",startupImage:["/voto-forte-bandeira-icon.jpg"]}, other:{"codex-preview":"development","mobile-web-app-capable":"yes","apple-mobile-web-app-capable":"yes","apple-mobile-web-app-status-bar-style":"black-translucent"}, icons:{icon:"/voto-forte-bandeira-icon.jpg",shortcut:"/voto-forte-bandeira-icon.jpg",apple:"/voto-forte-bandeira-icon.jpg"} };
export default function RootLayout({children}:{children:React.ReactNode;}) { return <html lang="pt-BR" suppressHydrationWarning><head><script dangerouslySetInnerHTML={{__html:THEME_BOOTSTRAP_SCRIPT}} /></head><body className={`${geistSans.variable} ${geistMono.variable} antialiased`}><PwaInstaller /><AdaptivePerformance /><SignupMunicipalityEnhancer /><DashboardRuntimeEnhancers /><DashboardRouteViewEnhancer />{children}</body></html>; }
