"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { apiFetch } from "./supabase-client";

type Role = "adm" | "gestor" | "master" | "lideranca" | "liderado" | "eleitor";
type Category = "all" | "create" | "import" | "export" | "edit" | "delete" | "whatsapp" | "access" | "other";
type Activity = { id:string|number; actorEmail:string; actorName?:string; actorRole?:Role; action:string; detail:string; createdAt:string; category?:Exclude<Category,"all">; subjectName?:string|null; subjectKind?:string|null; district?:string|null; ownerEmail?:string|null; exportId?:string|null; importSessionId?:string|null; itemCount?:number; districtCount?:number };
type Feed = { currentUserRole?:Role; users?:Array<{id:number;email:string;name:string;accessRole:Role;status:string;readOnly?:boolean}>; logs?:Activity[]; imports?:Activity[]; exports?:Activity[] };
type Item = { recordId:number; ownerEmail:string; snapshot:Record<string,unknown>; current:Record<string,unknown>|null; available:boolean };
type Detail = { kind:"import"|"export"; key:string; total:number; items:Item[] };

const roleLabel:Record<Role,string>={adm:"ADM",gestor:"Gestor",master:"Master",lideranca:"Liderança",liderado:"Liderado",eleitor:"Eleitor"};
const filters:Array<{key:Category;label:string}>=[{key:"all",label:"Todas"},{key:"create",label:"Cadastros"},{key:"import",label:"Importações"},{key:"export",label:"Exportações"},{key:"edit",label:"Edições"},{key:"delete",label:"Exclusões"},{key:"whatsapp",label:"WhatsApp"}];
const dt=(v:string)=>new Date(v).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"});
const initials=(v:string)=>v.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();

export default function AdministrationActivityEnhancer(){
  const [panel,setPanel]=useState<HTMLElement|null>(null);
  const [auditTarget,setAuditTarget]=useState<HTMLElement|null>(null);
  const [usersTarget,setUsersTarget]=useState<HTMLElement|null>(null);
  const [active,setActive]=useState("");
  const [feed,setFeed]=useState<Feed>({});
  const [category,setCategory]=useState<Category>("all");
  const [actor,setActor]=useState("all");
  const [period,setPeriod]=useState("7d");
  const [query,setQuery]=useState("");
  const [detail,setDetail]=useState<Detail|null>(null);
  const [editing,setEditing]=useState<Item|null>(null);
  const [form,setForm]=useState<Record<string,string>>({});
  const [loading,setLoading]=useState(false);
  const [message,setMessage]=useState("");

  const load=useCallback(async()=>{setLoading(true);setMessage("");try{const r=await apiFetch("/api/administration/activity?limit=300",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Falha ao carregar auditoria");setFeed(d)}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar auditoria")}finally{setLoading(false)}},[]);

  useEffect(()=>{let last:HTMLElement|null=null;const detect=()=>{const p=document.querySelector<HTMLElement>(".vf-hierarchy-panel");if(p!==last){last=p;setPanel(p);if(p)void load()}if(!p){setAuditTarget(null);setUsersTarget(null);return}const a=p.querySelector<HTMLButtonElement>(".vf-access-tabs button.active");setActive(a?.textContent?.trim().toLowerCase()||"");const cards=Array.from(p.querySelectorAll<HTMLElement>(".vf-access-list-card"));const audit=cards.find(c=>c.querySelector("small")?.textContent?.trim().toUpperCase()==="AUDITORIA")||null;if(audit)audit.dataset.vfRichAudit="true";setAuditTarget(audit);setUsersTarget(p.querySelector<HTMLElement>(".vf-hierarchy-tree"))};detect();const o=new MutationObserver(detect);o.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["class"]});document.addEventListener("click",detect,true);return()=>{o.disconnect();document.removeEventListener("click",detect,true)}},[load]);

  const activities=useMemo(()=>{const m=new Map<string,Activity>();[...(feed.logs||[]),...(feed.imports||[]),...(feed.exports||[])].forEach(x=>m.set(String(x.id),x));return [...m.values()].sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt))},[feed]);
  const actors=useMemo(()=>{const m=new Map<string,string>();activities.forEach(x=>m.set(x.actorEmail,x.actorName||x.actorEmail));return [...m.entries()].sort((a,b)=>a[1].localeCompare(b[1],"pt-BR"))},[activities]);
  const filtered=useMemo(()=>{const max=period==="24h"?86400000:period==="7d"?604800000:period==="30d"?2592000000:Infinity;const q=query.trim().toLowerCase();return activities.filter(x=>(category==="all"||x.category===category)&&(actor==="all"||x.actorEmail===actor)&&(!Number.isFinite(max)||Date.now()-+new Date(x.createdAt)<=max)&&(!q||[x.actorName,x.actorEmail,x.action,x.detail,x.subjectName,x.subjectKind,x.district].filter(Boolean).join(" ").toLowerCase().includes(q)))},[activities,category,actor,period,query]);
  const today=useMemo(()=>{const k=new Date().toLocaleDateString("pt-BR",{timeZone:"America/Sao_Paulo"});const xs=activities.filter(x=>new Date(x.createdAt).toLocaleDateString("pt-BR",{timeZone:"America/Sao_Paulo"})===k);return{create:xs.filter(x=>x.category==="create").length,imported:xs.filter(x=>x.category==="import").reduce((s,x)=>s+Number(x.itemCount||0),0),exported:xs.filter(x=>x.category==="export").reduce((s,x)=>s+Number(x.itemCount||0),0),edited:xs.filter(x=>x.category==="edit").length}},[activities]);
  const maskedAdmins=useMemo(()=>feed.currentUserRole==="gestor"?(feed.users||[]).filter(x=>x.readOnly&&x.accessRole==="gestor"&&x.status==="active"):[],[feed]);

  async function openDetail(a:Activity){const kind=a.category==="import"?"import":a.category==="export"?"export":null;const key=kind==="import"?a.importSessionId:a.exportId;if(!kind||!key)return;setLoading(true);try{const p=new URLSearchParams({kind,key,limit:"100"});if(a.ownerEmail)p.set("owner",a.ownerEmail);const r=await apiFetch(`/api/administration/activity?${p}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Falha ao abrir lote");setDetail(d)}catch(e){setMessage(e instanceof Error?e.message:"Falha ao abrir lote")}finally{setLoading(false)}}
  function beginEdit(i:Item){if(!i.available||!i.current)return;const c=i.current;setEditing(i);setForm({name:String(c.name??""),phone:String(c.phone??""),kind:String(c.kind??"Eleitor"),district:String(c.district??""),cep:String(c.cep??""),street:String(c.street??""),number:String(c.number??""),leader:String(c.leader??""),city:String(c.city??""),state:String(c.state??"")})}
  async function saveEdit(e:React.FormEvent){e.preventDefault();if(!editing)return;setLoading(true);try{const r=await apiFetch("/api/records",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:editing.recordId,payload:form})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Falha ao editar contato");setEditing(null);setMessage("Contato atualizado. A alteração ficou registrada na auditoria.");void load()}catch(err){setMessage(err instanceof Error?err.message:"Falha ao editar contato")}finally{setLoading(false)}}
  async function remove(i:Item){if(!i.available||!window.confirm("Excluir este contato da base? O histórico do lote será preservado."))return;const r=await apiFetch(`/api/records?id=${i.recordId}`,{method:"DELETE"});const d=await r.json();if(!r.ok){setMessage(d.error||"Falha ao excluir contato");return}setMessage("Contato excluído da base. O histórico foi preservado.");setDetail(v=>v?{...v,items:v.items.map(x=>x.recordId===i.recordId?{...x,available:false,current:null}:x)}:v);void load()}

  if(!panel)return null;
  const masked=active.includes("gerenciar")&&usersTarget&&maskedAdmins.length?createPortal(<section className="vf-masked-admins"><header><div><small>GESTORES DO SISTEMA</small><h4>Visão administrativa</h4></div><span>Somente leitura</span></header><p>Para Gestores, usuários ADM aparecem como <b>Gestor</b>. O cargo real continua protegido e não pode ser alterado.</p><div>{maskedAdmins.map(u=><article key={u.id}><b>{initials(u.name)}</b><div><strong>{u.name}</strong><small>{u.email}</small><span>Gestor</span></div><em>Somente leitura</em></article>)}</div></section>,usersTarget):null;
  const audit=active.includes("auditoria")&&auditTarget?createPortal(<div className="vf-rich-audit"><div className="vf-rich-audit-summary"><article><small>CADASTROS HOJE</small><b>{today.create}</b></article><article><small>IMPORTADOS HOJE</small><b>{today.imported.toLocaleString("pt-BR")}</b></article><article><small>EXPORTADOS HOJE</small><b>{today.exported.toLocaleString("pt-BR")}</b></article><article><small>EDITADOS HOJE</small><b>{today.edited}</b></article></div><div className="vf-rich-audit-toolbar"><div>{filters.map(f=><button key={f.key} type="button" className={category===f.key?"active":""} onClick={()=>setCategory(f.key)}>{f.label}</button>)}</div><section><select value={actor} onChange={e=>setActor(e.target.value)}><option value="all">Todos os usuários</option>{actors.map(([email,name])=><option key={email} value={email}>{name}</option>)}</select><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="24h">24 horas</option><option value="7d">7 dias</option><option value="30d">30 dias</option><option value="all">Tudo</option></select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nome, bairro ou ação"/><button type="button" onClick={()=>void load()} disabled={loading}>Atualizar</button></section></div>{message?<p className="vf-rich-audit-message">{message}</p>:null}<div className="vf-rich-audit-list">{filtered.map(a=><article key={String(a.id)}><div className="vf-rich-avatar">{initials(a.actorName||a.actorEmail)}</div><div><header><p><strong>{a.actorName||a.actorEmail}</strong><span>{roleLabel[a.actorRole||"gestor"]}</span></p><time>{dt(a.createdAt)}</time></header><h5>{a.category==="create"&&a.subjectName?"Cadastrou novo contato":a.category==="import"?"Importou contatos":a.category==="export"?"Exportou contatos":a.action}</h5>{a.subjectName?<p className="vf-rich-subject"><b>{a.subjectName}</b>{a.subjectKind?<span>{a.subjectKind}</span>:null}{a.district?<small>{a.district}</small>:null}</p>:null}<p>{a.category==="import"?`${Number(a.itemCount||0).toLocaleString("pt-BR")} contatos importados`:a.category==="export"?`${Number(a.itemCount||0).toLocaleString("pt-BR")} contatos · ${a.detail}`:a.detail}</p>{a.category==="import"||a.category==="export"?<button className="vf-open-lot" type="button" onClick={()=>void openDetail(a)}>Ver contatos</button>:null}</div></article>)}{!filtered.length?<p>Nenhuma atividade encontrada.</p>:null}</div></div>,auditTarget):null;
  const modal=detail?createPortal(<div className="vf-activity-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDetail(null)}}><section className="vf-activity-modal"><header><div><small>{detail.kind==="import"?"LOTE IMPORTADO":"LOTE EXPORTADO"}</small><h3>{detail.total.toLocaleString("pt-BR")} contatos</h3></div><button type="button" onClick={()=>setDetail(null)}>×</button></header><div className="vf-activity-contacts">{detail.items.map(i=>{const c=i.current??i.snapshot;let phone=String(c.phone??"").replace(/\D/g,"");if(phone.length===10||phone.length===11)phone=`55${phone}`;return <article key={i.recordId}><div><strong>{String(c.name??"Contato sem nome")}</strong><small>{String(c.kind??"Eleitor")} · {String(c.district??"Sem bairro")} · {i.ownerEmail}</small>{!i.available?<em>Snapshot preservado</em>:null}</div><div>{phone?<a href={`https://wa.me/${phone}`} target="_blank" rel="noreferrer">WhatsApp</a>:null}<button type="button" disabled={!i.available} onClick={()=>beginEdit(i)}>Editar</button><button type="button" className="danger" disabled={!i.available} onClick={()=>void remove(i)}>Excluir</button></div></article>})}</div></section></div>,document.body):null;
  const edit=editing?createPortal(<div className="vf-activity-modal-backdrop"><form className="vf-activity-edit" onSubmit={saveEdit}><header><h3>Editar contato</h3><button type="button" onClick={()=>setEditing(null)}>×</button></header>{[["name","Nome"],["phone","WhatsApp"],["district","Bairro"],["leader","Liderança"],["cep","CEP"],["street","Rua"],["number","Número"],["city","Cidade"],["state","Estado"]].map(([k,l])=><label key={k}>{l}<input value={form[k]||""} onChange={e=>setForm(v=>({...v,[k]:e.target.value}))}/></label>)}<label>Perfil<select value={form.kind||"Eleitor"} onChange={e=>setForm(v=>({...v,kind:e.target.value}))}><option>Eleitor</option><option>Liderança</option></select></label><footer><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button type="submit" disabled={loading}>Salvar</button></footer></form></div>,document.body):null;
  return <>{masked}{audit}{modal}{edit}</>;
}
